Add files via upload

diff --git a/sigchk b/sigchk
--- a/sigchk
+++ b/sigchk
@@ -1,7 +1,7 @@
 #!/bin/sh
 {
-# bb2d38c9e660ea1ae3092a1837e07db1
-# f6d9eea31c9305e3699d0002bfb9b056a021ec7b62bf5582f8013d63a694259480148fd81a979df0f6995ea00fb3f89af0f4d566ca037eb2d3fe48369c1f1a01
+# 2cc0dd3212b463afe948c0a5540acd54
+# 97bc403c3a6c7bfd3a7577d473114ea6bb0758b9ad375745c64986e7fc7369a9f0368496edbb16e53a38345c5235321784e63a7ae6684dfa81e7b05a66c6fa0f
 set -u
 
 necho() {
@@ -54,7 +54,7 @@ case "${count:-"0"}" in
 		return 0
 	;;
 	*)
-		printf -- '%s\n' "${name}: please install: ${*}"
+		printf -- '%s\n' "${name:-"${0##*"/"}"}: please install: ${*}"
 		exit 1	
 	;;
 esac
@@ -378,44 +378,8 @@ while getopts "cCfFvVtTpPdDsSxXhHqQ-:" OPT; do
 					show_help
 				;;
 				version)
-					printf -- '%s\n' "${name} ${version:-"1.2.0"}"
+					printf -- '%s\n' "${name:-"${0##*"/"}"} ${version:-"1.2.1"}"
 					exit 0
-				;;
-				dev|indev|dev-mode|in-dev)
-					case "${dev_mode:-"0"}" in
-						0)
-							if [ -w "${0}" ]; then
-								if sed -i 's/^dev_mode=0$/dev_mode=1/' -- "${0}"; then
-									dev_mode=1
-									printf -- '%s\n' "${name}: The dev mode is on" 1>&2
-								else
-									printf -- '%s\n' "${name}: Cannot rewrite ${0##*"/"}" 1>&2
-									exit 1
-								fi
-							else
-								printf -- '%s\n' "${name}: please run as root" 1>&2
-								exit 1
-							fi
-						;;
-					esac
-				;;
-				no-dev|no-dev-mode|not-in-dev)
-					case "${dev_mode:-"1"}" in
-						1)
-							if [ -w "${0}" ]; then
-								if sed -i 's/^dev_mode=1$/dev_mode=0/' -- "${0}"; then
-									dev_mode=0
-									printf -- '%s\n' "${name}: The dev mode is off" 1>&2
-								else
-									printf -- '%s\n' "${name}: Cannot rewrite ${0##*"/"}" 1>&2
-									exit 1
-								fi
-							else
-								printf -- '%s\n' "${name}: please run as root" 1>&2
-								exit 1
-							fi
-						;;
-					esac
 				;;
 				q|Q|quiet)
 					exec 2>/dev/null
@@ -442,7 +406,7 @@ case "${colourize:-"0"}" in
 		unset "reset" "bold" "faint" "italic" "underline" "blink" "reverse" "conceal" "crossed_out" "black" "red" "green" "yellow" "blue" "magenta" "cyan" "white" "light_black" "light_red" "light_green" "light_yellow" "light_blue" "light_magenta" "light_cyan" "light_white"
 	;;
 esac
-bold_name="${bold:-""}${name}${reset:-""}"
+bold_name="${bold:-""}${name:-"${0##*"/"}"}${reset:-""}"
 green_ok="${green:-""}OK${reset:-""}"
 red_failed="${red:-""}FAILED${reset:-""}"
 if devchk; then
@@ -1143,26 +1107,33 @@ esac
 }
 
 process_exe_state() {
-local "line" "start"
+local "line" "start" "strict_update"
 strict_full=""
 while read -r "line"; do
 	case "${strict:-"0"}" in
-		1)
-			case "${line}" in
-				"Subject"*)
-					strict_full="${strict_full}${line##*": "}"
-				;;
-				"Issuer"*)
-					strict_full="${strict_full}${line##*": "}"
-				;;
-				"Serial"*)
-					strict_full="${strict_full}${line##*": "}"
-					continue
-				;;
-			esac
+			1)
+				case "${strict_update:-"1"}" in
+					1)
+						case "${line}" in
+							"Subject"*)
+								strict_full="${strict_full}${line##*": "}"
+							;;
+							"Issuer"*)
+									strict_full="${strict_full}${line##*": "}"
+									;;
+							"Serial"*)
+								strict_full="${strict_full}${line##*": "}"
+								continue
+							;;
+						esac
+					;;
+				esac
 		;;
 	esac
 	case "${line}" in
+		"Timestamp Verified by:"*)
+			strict_update=0
+		;;
 		"Current message digest"*)
 			old="${line##*": "}"
 		;;
@@ -1227,6 +1198,88 @@ case "${old:-"none"}_${as:-"none"}_${to:-"none"}" in
 esac
 }
 
+
+detect_osslsigncode() {
+local "osslsigncode_ver"
+osslsigncode_ver=$( osslsigncode --version 2>/dev/null )
+osslsigncode_ver="${osslsigncode_ver%%$'\n'*}"
+osslsigncode_ver="${osslsigncode_ver%", using:"*}"
+osslsigncode_ver="${osslsigncode_ver#*"osslsigncode "}"
+case "${osslsigncode_ver:-""}" in
+	[0-1]"."?*|"2.0.0")
+		is_new_osslsigncode=0
+		return 1
+	;;
+	*)
+		is_new_osslsigncode=1
+		case "${osslsigncode_ver:-""}" in
+			"2.1.0")
+				untrusted="untrusted"
+			;;
+		esac
+		cert="/etc/ssl/certs/ca-certificates.crt"
+		if ! [ -e "${cert}" ]; then
+			echo "${0##*"/"}: ${cert##*"/"}: no certificate database found" 1>&2
+			exit 1
+		fi
+		osslsigncode_dtmp=$( mktemp -p "/tmp/" -d "${name:-"${0##*"/"}"}-XXXXXXXXXXXX" 2>/dev/null )
+		case "${osslsigncode_dtmp:-""}" in
+			"")
+				osslsigncode_dtmp="/tmp/${name:-"${0##*"/"}"}-000000000000"
+				if ! [ -e "${tmp}" ]; then
+					if ! mkdir -- "/tmp/${name:-"${0##*"/"}"}-000000000000"; then
+						echo "${0##*"/"}: ${osslsigncode_dtmp}: cannot make a temp directory" 1>&2
+						exit 1
+					fi
+				fi
+			;;
+		esac
+		if [ -d "${osslsigncode_dtmp:-""}" ]; then
+			trap 'process_tmp_clean 130' INT
+			trap 'process_tmp_clean' EXIT TERM QUIT
+		else
+			return 1
+		fi
+		return 0
+	;;
+esac
+}
+
+osslsigncode_extract() {
+local "tmp_exe"
+case "${is_new_osslsigncode:-"1"}" in
+	0)
+		if ! osslsigncode extract-signature -in "${1}" -out /dev/null >/dev/null 2>&1; then
+			return 1
+		fi
+	;;
+	*)
+		tmp_exe="${osslsigncode_dtmp:-"/tmp"}/${1##*"/"}"
+		if [ -f "${tmp_exe}" ]; then
+			if ! rm -- "${tmp_exe}"; then
+				echo "${name:-"${0##*"/"}"}: ${tmp_exe}: cannot remove temporary file" 1>&2
+				return 1
+			fi
+		fi
+		if ! osslsigncode extract-signature -in "${1}" -out "${tmp_exe}" >/dev/null 2>&1; then
+			return 1
+		fi
+	;;
+esac
+}
+
+osslsigncode_verify() {
+local "tmp_exe"
+case "${is_new_osslsigncode:-"1"}" in
+	0)
+		osslsigncode verify -in "${1}" 2>/dev/null
+	;;
+	*)
+		osslsigncode verify -CAfile "${cert}" -"${untrusted:-"TSA-CAfile"}" "${cert}" -in "${1}" 2>/dev/null
+	;;
+esac
+}
+
 process_exe() {
 local "sha_one" "total"
 if ! process_local_checksums "${1}"; then return 1; fi
@@ -1238,13 +1291,13 @@ if process_xattr "${1}"; then
 		return 1
 	fi
 fi
-if osslsigncode extract-signature -in "${1}" -out /dev/null >/dev/null 2>&1; then
+if osslsigncode_extract "${1}"; then
 	case "${dry_run:-"0"}" in
 		1)
 			return 0
 		;;
 	esac
-	strict_full=$( osslsigncode verify -in "${1}" 2>/dev/null | process_exe_state )
+	strict_full=$( osslsigncode_verify "${1}" | process_exe_state )
 	case "${?}" in
 		0)
 			process_recovery_make "${1}"
@@ -1874,14 +1927,26 @@ fi
 
 process_tmp_clean() {
 case "${dtmp:-""}" in
-	"/tmp/${name}-"????????????)
-		rm -fr -- "${dtmp}"
+	"/tmp/${name:-"${0##*"/"}"}-"????????????)
+		if [ -d "${dtmp}" ]; then
+			rm -fr -- "${dtmp}"
+		fi
 	;;
 esac
-unset "dtmp"
+case "${osslsigncode_dtmp:-""}" in
+	"/tmp/${name:-"${0##*"/"}"}-"????????????)
+		if [ -d "${osslsigncode_dtmp}" ]; then
+			rm -fr -- "${osslsigncode_dtmp}"
+		fi
+	;;
+esac
+unset "dtmp" "osslsigncode_dtmp"
 case "${1:-"0"}" in
 	130)
 		exit 130
+	;;
+	*)
+		exit "${code:-"0"}"
 	;;
 esac
 }
@@ -1903,7 +1968,7 @@ if process_xattr "${1}"; then
 	fi
 fi
 dpath=$( realpath --no-symlinks -- "${1}" )
-dtmp=$( mktemp -p "/tmp/" -d "${name}-XXXXXXXXXXXX" 2>/dev/null )
+dtmp=$( mktemp -p "/tmp/" -d "${name:-"${0##*"/"}"}-XXXXXXXXXXXX" 2>/dev/null )
 if [ -d "${dtmp:-""}" ]; then
 	trap 'process_tmp_clean 130' INT
 else
@@ -2302,7 +2367,7 @@ if process_xattr "${1}"; then
 fi
 if type zip >/dev/null 2>&1; then
 	dpath=$( realpath --no-symlinks -- "${1}" )
-	dtmp=$( mktemp -p "/tmp/" -d "${name}-XXXXXXXXXXXX" 2>/dev/null )
+	dtmp=$( mktemp -p "/tmp/" -d "${name:-"${0##*"/"}"}-XXXXXXXXXXXX" 2>/dev/null )
 	if [ -d "${dtmp:-""}" ]; then
 		trap 'process_tmp_clean 130' INT
 	else
@@ -2493,11 +2558,12 @@ local "name"
 name="${0##*"/"}"
 selfcheck
 setdevmode
-hash_mark="user.${name}.hash"
+hash_mark="user.${name:-"${0##*"/"}"}.hash"
 pkgchk "awk" "b2sum" "bzip2" "find" "grep" "gzip" "md5sum" "osslsigncode" "realpath" "sed" "stat" "tac" "unzip" "wc" "xz"
 data_exceptions
 setcert
 set_colour
+detect_osslsigncode
 setopt "${@}"
 exit "${code:-"0"}"
 }
